### ISSUE TITLE
when resilvering check fails to run. 

### ISSUE THREAD

**Issue by bdeluca** [sensu-plugins/sensu-plugins-zfs#12]
`Check failed to run: no time information in "", ["/opt/sensu/embedded/lib/ruby/2.4.0/time.rb:254:in `make_time'", "/opt/sensu/embedded/lib/ruby/2.4.0/time.rb:370:in `parse'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-zfs-2.0.1/lib/sensu-plugins-zfs/zpool.rb:29:in `scrubbed_at'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-zfs-2.0.1/bin/check-zpool.rb:78:in `check_recently_scrubbed'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-zfs-2.0.1/bin/check-zpool.rb:43:in `block in run'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-zfs-2.0.1/bin/check-zpool.rb:39:in `each'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-zfs-2.0.1/bin/check-zpool.rb:39:in `run'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugin-1.4.5/lib/sensu-plugin/cli.rb:58:in `block in '"]`

**Comment by bdeluca** [comment]
Sorry for the terrible formatting, in the description. 
A pool should be checked for resilvering/degraded state. 



 ```
 pool: store
 state: DEGRADED
status: One or more devices is currently being resilvered.  The pool will
        continue to function in a degraded state.
action: Wait for the resilver to complete.
        Run 'zpool status -v' to see device specific details.
  scan: resilver in progress since Mon Aug 20 12:05:19 2018
    112T scanned out of 451T at 3.19G/s, 1d06h to go
    0 resilvered
```

**Comment by ipaqmaster** [comment]
Most of my servers and their zpool's are also outputting this `Check failed to run: no time information in "",` text as well for the last few weeks.
